config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about'
    namespace :public do
      post 'orders/info'
      get 'orders/complete'
      post 'orders/create'
      resources :orders, only: [:new, :index, :show]

      post 'cart_items/create'
      delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'
      delete 'cart_items/destroy/:id' => 'cart_items#destroy', as: 'cart_item_destroy'
      patch 'cart_items/update/:id' => 'cart_items#update', as: 'cart_item_update'

      resources :cart_items, only: [:index]

      get 'customers/withdrawal' => 'customers#withdrawal'
      patch 'customers/withdraw' => 'customers#withdraw'
      get 'customers/mypage' => 'customers#show'
      get 'customers/edit'
      patch 'customers/update' => 'customers#update'

      resources :items, only: [:index, :show]
    end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get '/' => 'homes#top'
    get 'orders/show/:id' => 'orders#show'
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
    patch 'customers/update/:id' => 'customers#update', as: 'customers_update'
    get 'items/index'
    get 'items/new'
    post 'items/create'
    get 'items/show/:id' => 'items#show', as: 'items_show'
    get 'items/edit/:id' => 'items#edit', as: 'items_edit'
    patch 'items/update/:id' => 'items#update', as: 'items_update'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items

  has_one_attached :image_id


  def with_tax_price
    (price*1.1).floor
  end


  def get_profile_image(width, height)
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image_id.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_show_path(@item)
  end

  def show
    @items = Item.find(params[:id])
  end

  def edit
    @items = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_show_path(@item.id)
  end


private


  def item_params
    params.require(:item).permit( :name, :introduction, :image_id, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-8 mt-3 px-5">
            <p>商品編集</p>
            <%= form_with model: @items, url: admin_items_update_path(@items) do |f| %>
            <table>
                <tr>
                    <td>
                        商品画像
                    </td>
                    <td>
                        <div class="form_group">
                            <%= f.file_field :image_id, accept: "image/*" %>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        商品名
                    </td>
                    <td>
                        <div class="form_group">
                            <%= f.text_field :name, :placeholder => "#{@items.name}" %>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        商品説明
                    </td>
                    <td>
                        <div class="form_group">
                            <%= f.text_area :introduction, :placeholder => "#{@items.introduction}" %>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        税抜価格
                    </td>
                    <td>
                        <div class="form_group">
                            <%= f.text_field :price, :placeholder => "#{@items.price}" %>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td> </td>
                    <td>
                        <div class="form_group">
                            <%= f.submit "変更を保存", class: "btn btn-success" %>
                        </div>
                    </td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-3 px-5">
      <p>商品一覧</p>
      <%= link_to admin_items_new_path do %>
      <div class="text-right">
        <button class="btn btn-lg">
          <i class="fa-solid fa-circle-plus"></i>
        </button>
      </div>
      <% end %>

      <table class="table">
        <thead>
          <tr bgcolor="#cccccc">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= link_to admin_items_show_path(item.id) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td>
              <%= item.price %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div style="text-align:center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-3 px-5">
      <%= form_with model: @item, url: admin_items_create_path do |f| %>
      <table>
        <tr>
          <td>
            商品画像
          </td>
          <td>
            <div class="form_group">
              <%= f.file_field :image_id, accept: "image/*" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>
            商品名
          </td>
          <td>
            <div class="form_group">
              <%= f.text_field :name, placeholder: "商品名" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>
            商品説明
          </td>
          <td>
            <div class="form_group">
              <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>
            税抜価格
          </td>
          <td>
            <div class="form_group d-flex flex-row">
              <%= f.text_field :price,placeholder: "1000" %><span>円</span>
            </div>
          </td>
        </tr>

        <tr>
          <td> </td>
          <td>
            <%= f.submit "新規登録", class: "btn btn-success" %>
          </td>
        </tr>
      </table>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mt-3">
    <p>商品詳細</p>
    <div class="col-md-3 mt-5">
      <%= image_tag @items.get_profile_image(150,150) %>
    </div>
    <div class="col-md-7 mt-5">
      <table>
        <tr>
          <td>
            商品名
          </td>
          <td>
            <%= @items.name %>
          </td>
        </tr>

        <tr>
          <td>
            商品説明
          </td>
          <td>
            <%= @items.introduction %>
          </td>
        </tr>

        <tr>
          <td>
            税込価格<br>
            (税抜価格)
          </td>
          <td>
            <%= @items.price %>
          </td>
        </tr>

        <tr>
          <td>
            <%= link_to admin_items_edit_path(@items) do %>
            <button class="btn btn-success">
              編集する
            </button>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>