config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about'
    namespace :public do
      post 'orders/info'
      get 'orders/complete'
      post 'orders/create'
      resources :orders, only: [:new, :index, :show]

      post 'cart_items/create'
      delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy'
      delete 'cart_items/destroy/:id' => 'cart_items#destroy', as: 'cart_item_destroy'
      patch 'cart_items/update/:id' => 'cart_items#update', as: 'cart_item_update'

      resources :cart_items, only: [:index]

      get 'customers/withdrawal' => 'customers#withdrawal'
      patch 'customers/withdraw' => 'customers#withdraw'
      get 'customers/mypage' => 'customers#show'
      get 'customers/edit'
      patch 'customers/update' => 'customers#update'

      resources :items, only: [:index, :show]
    end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get '/' => 'homes#top'
    get 'orders/show/:id' => 'orders#show'
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
    patch 'customers/update/:id' => 'customers#update', as: 'customers_update'
    get 'items/index'
    get 'items/new'
    post 'items/create'
    get 'items/show/:id' => 'items#show', as: 'items_show'
    get 'items/edit/:id' => 'items#edit', as: 'items_edit'
    patch 'items/update/:id' => 'items#update', as: 'items_update'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer


  def subtotal
    (item.with_tax_price)*amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items

  has_one_attached :image_id


  def with_tax_price
    (price*1.1).floor
  end


  def get_profile_image(width, height)
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image_id.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  has_many :order_dateils
  belongs_to :customer

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_show_path(@item)
  end

  def show
    @items = Item.find(params[:id])
  end

  def edit
    @items = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_show_path(@item.id)
  end


private


  def item_params
    params.require(:item).permit( :name, :introduction, :image_id, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2ee7dc101e.js" crossorigin="anonymous"></script>

  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background: #000000">
        <div class="container">

          <a class="navbar-brand p-3" href="/">
            naganocake
          </a>
          <div class="text-light">
                  <p>ようこそ、<%= current_customer.last_name %>さん！</p>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                 aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if customer_signed_in? %>


              <li class="nav-item">
                  <%= link_to public_customers_mypage_path, class: 'nav-link text-light' do %>
                  マイページ
                  <% end %>
              </li>


              <li class="nav-item">
                <%= link_to public_items_path, class: 'nav-link text-light' do %>
                商品一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                カート
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                ログアウト
                <% end %>
              </li>


              <% elsif admin_signed_in? %>

              <li class="nav-item">
                  <%= link_to admin_items_index_path, class: 'nav-link text-light' do %>
                  商品一覧
                  <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_customers_index_path, class: 'nav-link text-light' do %>
                会員一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_path, class: 'nav-link text-light' do %>
                注文履歴一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                ログアウト
                <% end %>
              </li>

              <% else %>

              <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                  About
                  <% end %>
              </li>

              <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                  商品一覧
                  <% end %>
              </li>

              <li class="nav-item">
                  <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                  新規登録
                  <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                ログイン
                <% end %>
              </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>